server:
  port: 1298
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Breeze-zhe/aibuy-config.git
          username: Breeze-zhe
          password: weijiazhe123
